Fix headings in accordance with WCAG
Uninett/nav-landing-page pull request #9
Opened 2023-01-10 10:57 UTC by podliashanyk

Following WCAG requirements are satisfied:

- WCAG 2.0 - 1.3.1
- WCAG 2.0 - 2.4.10
- WCAG 2.0 - 2.4.6

In other words:

- One h1 per page (hidden in our case)
- All headings are in logical order and there are no "jumps" between headings (f.e. from h2 to h4)
- HTML headers are not used as a replacement for lists
- All sections have headers
- All headers have descriptive and informative names
- Everything that looks like heading is coded as one

2023-01-11 08:52 UTC, lunkwill42 requested changes
This is nice, but I don't like the new "Features" heading as is.

Also, since you're working against the `migrate-blog` branch in this instance, there is a much-needed followup to this in the blog list page: The markdown renderer that renders the content of each individual blog posting in the list starts all headings at `<h1>`, causing multiple of them in the same page. We need to find out whether there is some way to tell the renderer to start at `<h2>` instead.

2023-01-11 08:52 UTC, lunkwill42 commented on layouts/index.html
> +                    <h2 class="super-heading">Features</h2>
This actually kind of breaks the design a bit, IMHO. For the seeing, it is obvious that this section lists features, with the four large icons describing the main features.  I suggest this heading is also hidden.

2023-01-12 13:08 UTC, podliashanyk commented
> Also, since you're based on the `migrate-blog` branch in this instance, there is a much-needed followup to this in the blog list page: The markdown renderer that renders the content of each individual blog posting in the list starts all headings at `<h1>`, causing multiple of them in the same page. We need to find out whether there is some way to tell the renderer to start at `<h2>` instead.

Since one and just one h1 per page is not enforced by Norwegian law (it is a AAA requirement), and since I haven't found a quick fix for this, I have created #13 to work on this issue separately. 🙂

2023-01-17 09:46 UTC, lunkwill42 approved these changes
:+1: But there's a merge conflict now that you have so many PR's in-flight ...

2023-01-17 12:22 UTC, merged